version: '2.2'
services:
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - MSSQL_PID=Developer
            - SA_PASSWORD=1234@abcd
            - ACCEPT_EULA=Y
            - MSSQL_AGENT_ENABLED=true
        restart: always
        volumes:
            - storage_data:/var/opt/mssql
        ports: 
            - 1433:1433
volumes: 
    storage_data:
        external: false