version: '2.2'
services:
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=1234@abcd
            - MSSQL_PID=Developer
        restart: always
        volumes:
            - mssql:/var/opt/mssql
        ports: 
            - 1433:1433
volumes: 
    mssql:
        external: false